[package]
name = "smartfox"
version = "0.1.0"
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]

[dependencies]
regex = "0.2"
lazy_static = "0.2"

futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"

serde = "0.9"
serde_json = "0.9"
